### ISSUE TITLE
Reference to MGRS

### ISSUE THREAD

**Issue by kr-stn** [justinelliotmeyers/Sentinel-2-Shapefile-Index#2]
Hi,

Is the shapefile identical with the Military Grid Reference System published at: http://earth-info.nga.mil/GandG/coordsys/grids/universal_grid_system.html or did you make special changes to it?

Just asking because I am not sure if ESAs implementation of the MGRS differs from the official one.

cheers

**Comment by justinelliotmeyers** [comment]
I converted the kml the ESA provided.  I did not compare it to any NGA data.

**Comment by kr-stn** [comment]
Thank you for the answer. I'll ask ESA directly then if their KML has any changes compared to NGA.
